export const cleanupStatuses = [
	"ERROR",
	"SUBMITTED_TO_DCB",
	"PATRON_VERIFIED",
	"RESOLVED",
	"REQUEST_PLACED_AT_SUPPLYING_AGENCY",
	"CONFIRMED",
	"REQUEST_PLACED_AT_BORROWING_AGENCY",
	"REQUEST_PLACED_AT_PICKUP_AGENCY",
	"NO_ITEMS_SELECTABLE_AT_ANY_AGENCY",
];
