export const untrackedStatuses = [
	"ERROR",
	"SUBMITTED_TO_DCB",
	"CONFIRMED",
	"PATRON_VERIFIED",
	"RESOLVED",
	"NOT_SUPPLIED_CURRENT_SUPPLIER",
	"NO_ITEMS_SELECTABLE_AT_ANY_AGENCY",
	"CANCELLED",
	"HANDED_OFF_AS_LOCAL",
	"FINALISED",
];
