variables:
  FF_USE_FASTZIP: "true"
  # These can be specified per job or per pipeline
  ARTIFACT_COMPRESSION_LEVEL: "fast"
  CACHE_COMPRESSION_LEVEL: "fast"

default:
  image: node:20.15.1-bullseye
  tags:
    - ki-onprem

stages:
  - build
  - container

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - dcb-hub-admin-ui/.npm/
    - dcb-hub-admin-ui/node-modules/
    - .yarn
    - .npm

build:
  stage: build
  image: node:20.15.1-bullseye
  tags:
    - ki-onprem
  script:
    - export NPM_TOKEN="$NPMJS_TOKEN"
    - git config --global user.name "ianibbo"
    - git config --global user.email "ian.ibbotson@k-int.com"
    - cd dcb-hub-admin-ui
    - pwd
    - ls -al
    - echo " { \"releaseDate\":\"`date +"%Y-%m-%dT%H:%M:%S%z"`\", \"RELEASED_AT\":\"$RELEASED_AT\" } " > ./release-info.json
    - npm install
    - npm run semantic-release

build-container-image:
  image: docker:stable
  stage: container
  tags:
    - ki-onprem
  script:
    - echo Building container image
    - docker info

