default:
  image: node:latest
  before_script:
    - export NPM_TOKEN="$NPMJS_TOKEN"
    - git config --global user.name "ianibbo"
    - git config --global user.email "ian.ibbotson@k-int.com"
    - cd dcb-hub-admin-ui
  tags:
    - ki-onprem
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

stages:
  - build
  - release

build:
  stage: build
  script:
    - npm install
    # Tests can be run here

publish:
  stage: release
  only:
    - release
  script:
    - npm run semantic-release
