variables:
  FF_USE_FASTZIP: "true"
  # These can be specified per job or per pipeline
  ARTIFACT_COMPRESSION_LEVEL: "fast"
  CACHE_COMPRESSION_LEVEL: "fast"

default:
  image: 
    name: node:22.12.0-bullseye
    pull_policy: if-not-present

  tags:
    - ki-onprem

stages:
  - build
  - container

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - dcb-hub-admin-ui/.npm/
    - dcb-hub-admin-ui/node-modules/
    - .yarn
    - .npm

build:
  stage: build
  image: 
    name: node:22.12.0-bullseye
    pull_policy: if-not-present
  tags:
    - ki-onprem
  script:
    - export NPM_TOKEN="$NPMJS_TOKEN"
    - git config --global user.name "ianibbo"
    - git config --global user.email "ian.ibbotson@k-int.com"
    - cd dcb-hub-admin-ui
    - pwd
    - ls -al
    - echo " { \"releaseDate\":\"`date +"%Y-%m-%dT%H:%M:%S%z"`\", \"RELEASED_AT\":\"$RELEASED_AT\" } " > ./release-info.json
    - npm install
    - npm run semantic-release

build-container-image:
  image:
    name: moby/buildkit:rootless
    entrypoint: [""]
    pull_policy: if-not-present
  stage: container
  tags:
    - ki-onprem
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
    IMAGE: docker.libsdev.k-int.com/knowledgeintegration/ki-dcb-admin:next
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/generic-oidc-auth"'
  before_script:
    - mkdir -p ~/.docker
    - |
      AUTH="$(printf '%s' "$NEXUS_USER:$NEXUS_PASS" | base64 | tr -d '\n')"
      printf '{"auths":{"docker.libsdev.k-int.com":{"auth":"%s"}}}' "$AUTH" > ~/.docker/config.json
  script:
    - echo Building container image
    - cd dcb-hub-admin-ui
    - |
      buildctl-daemonless.sh build \
        --frontend dockerfile.v0 \
        --local context=. \
        --local dockerfile=./docker/production \
        --output type=image,name="$IMAGE",push=true
