services:
  dcb-admin:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    image: dcb-admin:local
    ports:
      # Maps the container's internal port 80 to the host's port 8080
      - "8080:80"
    environment:
      # These variables will be pulled from a local .env file
      - VITE_KEYCLOAK_URL=${VITE_KEYCLOAK_URL}
      - VITE_KEYCLOAK_ID=${VITE_KEYCLOAK_ID}
      - VITE_DCB_API_BASE=${VITE_DCB_API_BASE}
      - VITE_DCB_SEARCH_BASE=${VITE_DCB_SEARCH_BASE}
      - VITE_MUI_X_LICENSE_KEY=${VITE_MUI_X_LICENSE_KEY}
      # Defaults to root (/) if not specified in the .env file
      - VITE_PUBLIC_URL=${VITE_PUBLIC_URL:-/}
    restart: unless-stopped
