/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NetworkErrorRouteImport } from './routes/networkError'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as _authenticatedPatronRequestsIdIndexRouteImport } from './routes/__authenticated/patronRequests/$id/index'

const NetworkErrorRoute = NetworkErrorRouteImport.update({
  id: '/networkError',
  path: '/networkError',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedPatronRequestsIdIndexRoute =
  _authenticatedPatronRequestsIdIndexRouteImport.update({
    id: '/__authenticated/patronRequests/$id/',
    path: '/patronRequests/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/networkError': typeof NetworkErrorRoute
  '/patronRequests/$id/': typeof _authenticatedPatronRequestsIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/networkError': typeof NetworkErrorRoute
  '/patronRequests/$id': typeof _authenticatedPatronRequestsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/networkError': typeof NetworkErrorRoute
  '/__authenticated/patronRequests/$id/': typeof _authenticatedPatronRequestsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/logout' | '/networkError' | '/patronRequests/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/logout' | '/networkError' | '/patronRequests/$id'
  id:
    | '__root__'
    | '/login'
    | '/logout'
    | '/networkError'
    | '/__authenticated/patronRequests/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  NetworkErrorRoute: typeof NetworkErrorRoute
  _authenticatedPatronRequestsIdIndexRoute: typeof _authenticatedPatronRequestsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/networkError': {
      id: '/networkError'
      path: '/networkError'
      fullPath: '/networkError'
      preLoaderRoute: typeof NetworkErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated/patronRequests/$id/': {
      id: '/__authenticated/patronRequests/$id/'
      path: '/patronRequests/$id'
      fullPath: '/patronRequests/$id/'
      preLoaderRoute: typeof _authenticatedPatronRequestsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  NetworkErrorRoute: NetworkErrorRoute,
  _authenticatedPatronRequestsIdIndexRoute:
    _authenticatedPatronRequestsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
