// Statuses which users should NOT be able to check for updates
export const untrackedStatuses = [
	"ERROR",
	"SUBMITTED_TO_DCB",
	"CONFIRMED",
	"PATRON_VERIFIED",
	"RESOLVED",
	"NOT_SUPPLIED_CURRENT_SUPPLIER",
	"NO_ITEMS_SELECTABLE_AT_ANY_AGENCY",
	"CANCELLED",
	"HANDED_OFF_AS_LOCAL",
	"FINALISED",
];

// All non-terminal statuses and ERROR after DCB-1346
export const cleanupStatuses = [
	"ERROR",
	"SUBMITTED_TO_DCB",
	"PATRON_VERIFIED",
	"RESOLVED",
	"REQUEST_PLACED_AT_SUPPLYING_AGENCY",
	"CONFIRMED",
	"REQUEST_PLACED_AT_BORROWING_AGENCY",
	"PICKUP_TRANSIT",
	"RECEIVED_AT_PICKUP",
	"READY_FOR_PICKUP",
	"LOANED",
	"RETURN_TRANSIT",
];
