// Statuses which users should NOT be able to check for updates
export const untrackedStatuses = [
	"ERROR",
	"SUBMITTED_TO_DCB",
	"CONFIRMED",
	"PATRON_VERIFIED",
	"RESOLVED",
	"NOT_SUPPLIED_CURRENT_SUPPLIER",
	"NO_ITEMS_SELECTABLE_AT_ANY_AGENCY",
	"CANCELLED",
	"HANDED_OFF_AS_LOCAL",
	"FINALISED",
];

// All non-terminal statuses
// ERROR after DCB-1346
// NO_ITEMS_SELECTABLE_AT_ANY_AGENCY after 8.51.0
export const cleanupStatuses = [
	"ERROR",
	"SUBMITTED_TO_DCB",
	"PATRON_VERIFIED",
	"RESOLVED",
	"REQUEST_PLACED_AT_SUPPLYING_AGENCY",
	"CONFIRMED",
	"REQUEST_PLACED_AT_BORROWING_AGENCY",
	"REQUEST_PLACED_AT_PICKUP_AGENCY",
	"PICKUP_TRANSIT",
	"RECEIVED_AT_PICKUP",
	"READY_FOR_PICKUP",
	"LOANED",
	"RETURN_TRANSIT",
	"NO_ITEMS_SELECTABLE_AT_ANY_AGENCY",
];
