export const cleanupPatronRequestVisibility = {
	canonicalItemType: false,
	canonicalPtype: false,
	pickupLocationCode: false,
	status: false,
	previousStatus: false,
	nextExpectedStatus: false,
	errorMessage: false,
	elapsedTimeInCurrentStatus: false,
	pollCountForCurrentStatus: false,
	dateUpdated: false,
	patronHostlmsCode: false,
	suppliers: false,
	id: false,
	outOfSequenceFlag: false,
	isManuallySelectedItem: false,
	description: false,
	requesterNote: false,
	pickupRequestId: false,
	pickupRequestStatus: false,
	isExpeditedCheckout: false,
	itemBarcode: false,
	localItemStatus: false,
	rawLocalItemStatus: false,
	localItemId: false,
	localItemType: false,
	localRequestStatus: false,
	rawLocalRequestStatus: false,
	localRequestId: false,
	renewalCount: false,
	resolutionCount: false,
	activeWorkflow: false,
	supplyingAgencyCode: false,
	dateCreated: false, // Maybe give them this. But that's it
};
