import { GridColumnVisibilityModel } from "@mui/x-data-grid-premium";

export const defaultPatronRequestGroupVisibility: GridColumnVisibilityModel = {
	dateCreated: true,
	title: true,
	patronBarcode: true,
	patronHostlmsCode: true,
	supplyingAgencyCode: true,
	pickupLocationCode: true,
	pickupLibrary: false,
	status: true,
	canonicalItemType: false,
	canonicalPtype: false,
	previousStatus: false,
	nextExpectedStatus: false,
	errorMessage: false,
	outOfSequenceFlag: false,
	isManuallySelectedItem: false,
	dateUpdated: false,
	id: false,
	pickupRequestId: false,
	pickupRequestStatus: false,
	isExpeditedCheckout: false,
	itemBarcode: false,
	localItemStatus: false,
	rawLocalItemStatus: false,
	localItemId: false,
	localItemType: false,
	localRequestStatus: false,
	rawLocalRequestStatus: false,
	localRequestId: false,
	renewalCount: false,
	description: false,
	pollCountForCurrentStatus: false,
	elapsedTimeInCurrentStatus: false,
	requesterNote: false,
	resolutionCount: false,
};
