import { GridColumnVisibilityModel } from "@mui/x-data-grid-premium";

export const defaultSupplierRequestColumnVisibility: GridColumnVisibilityModel =
	{
		canonicalItemType: false,
		canonicalPtype: false,
		pickupLocationCode: false,
		pickupLibrary: false,
		patronHostlmsCode: true,
		previousStatus: false,
		nextExpectedStatus: false,
		errorMessage: false,
		outOfSequenceFlag: false,
		isManuallySelectedItem: false,
		dateUpdated: false,
		id: false,
		suppliers: false,
		supplyingAgencyCode: false,
		pickupRequestId: false,
		pickupRequestStatus: false,
		isExpeditedCheckout: false,
		description: false,
		requesterNote: false,
		pollCountForCurrentStatus: false,
		itemBarcode: false,
		localItemStatus: false,
		rawLocalItemStatus: false,
		localItemId: false,
		localItemType: false,
		localRequestStatus: false,
		rawLocalRequestStatus: false,
		localRequestId: false,
		renewalCount: false,
		elapsedTimeInCurrentStatus: false,
	};
