import { GridColumnVisibilityModel } from "@mui/x-data-grid-premium";

export const defaultPatronRequestColumnVisibility: GridColumnVisibilityModel = {
	canonicalItemType: false,
	canonicalPtype: false,
	pickupLocationCode: false,
	patronHostlmsCode: false,
	previousStatus: false,
	nextExpectedStatus: false,
	errorMessage: false,
	outOfSequenceFlag: false,
	isManuallySelectedItem: false,
	dateUpdated: false,
	id: false,
	description: false,
	requesterNote: false,
	activeWorkflow: false,
	pickupRequestId: false,
	pickupRequestStatus: false,
	pickupItemId: false,
	isExpeditedCheckout: false,
	itemBarcode: false,
	localItemStatus: false,
	rawLocalItemStatus: false,
	localItemId: false,
	localItemType: false,
	localRequestStatus: false,
	rawLocalRequestStatus: false,
	localRequestId: false,
	renewalCount: false,
	pollCountForCurrentStatus: false,
	elapsedTimeInCurrentStatus: false,
};
