export const exceptionPatronRequestColumnVisibility = {
	canonicalItemType: false,
	canonicalPtype: false,
	pickupLocationCode: false,
	previousStatus: true,
	status: false,
	errorMessage: true,
	elapsedTimeInCurrentStatus: false,
	pollCountForCurrentStatus: false,
	outOfSequenceFlag: false,
	dateUpdated: true,
	description: false,
	requesterNote: false,
	pickupRequestId: false,
	pickupRequestStatus: false,
	isExpeditedCheckout: false,
	itemBarcode: false,
	localItemStatus: false,
	rawLocalItemStatus: false,
	localItemId: false,
	localItemType: false,
	localRequestStatus: false,
	rawLocalRequestStatus: false,
	localRequestId: false,
	renewalCount: false,
	resolutionCount: false,
};
