import { AuditItem } from "./AuditItem";
import { ClusterRecord } from "./ClusterRecord";
import { Patron } from "./Patron";
import { PatronIdentity } from "./PatronIdentity";
import { RenewalStatus } from "./RenewalStatus";
import { SupplierRequest } from "./SupplierRequest";

export interface PatronRequest {
	id: string;
	dateCreated: string;
	dateUpdated: string;
	patronHostlmsCode: string;
	patron: Patron;
	requestingIdentity: PatronIdentity;
	bibClusterId: string;
	pickupLocationCode: string;
	pickupPatronId: string;
	pickupItemId: string;
	pickupItemType: string;
	pickupItemStatus: string;
	pickupRequestId: string;
	pickupRequestStatus: string;
	status: string;
	localRequestId: string;
	localRequestStatus: string;
	localItemId: string;
	localItemStatus: string;
	localItemType: string;
	localBibId: string;
	description: string;
	nextScheduledPoll: string;
	errorMessage: string;
	activeWorkflow: string;
	requesterNote: string;
	suppliers: [SupplierRequest];
	audit: AuditItem[];
	clusterRecord: ClusterRecord;
	previousStatus: string;
	pollCountForCurrentStatus: number;
	manualPollCountForCurrentStatus: number;
	autoPollCountForCurrentStatus: number;
	currentStatusTimestamp: string;
	nextExpectedStatus: string;
	outOfSequenceFlag: boolean;
	elapsedTimeInCurrentStatus: number;
	rawLocalItemStatus: string;
	rawLocalRequestStatus: string;
	localItemHostlmsCode: string;
	localItemAgencyCode: string;
	isManuallySelectedItem: boolean;
	resolutionCount: number;
	renewalCount: number;
	localRenewalCount: number;
	rawPickupItemStatus: string;
	rawPickupRequestStatus: string;
	pickupBibId: string;
	pickupItemBarcode: string;
	isExpeditedCheckout: boolean;
	localHoldingId: string;
	pickupHoldingId: string;
	renewalStatus: RenewalStatus;
}
